import EStyleSheet from "react-native-extended-stylesheet";

export const styles = EStyleSheet.create({
  container: { flex: 1, flexGrow: 1 },
  body: { flex: 1, flexGrow: 1 },
  title: {
    margin: 20,
    alignSelf: "center",
    color: "#fff",
    fontSize: 26,
    fontWeight: "bold",
  },
  loginLayout: {
    height: 430,
    marginHorizontal: 20,
    zIndex: 1,
  },
  loginBody: { overflow: "hidden", height: 420 },
  loginCard: {
    width: "100%",
    aspectRatio: 1,
    backgroundColor: "#fff",
    borderRadius: 40,
    borderEndEndRadius: 0,
  },
  loginCardFooter: {
    width: "102%",
    height: 100,
    backgroundColor: "#fff",
    borderRadius: 50,
    borderTopRightRadius: 30,
    borderTopEndRadius: 10,
    position: "absolute",
    bottom: 0,
    transform: [
      { translateY: "40%" },
      { translateX: "-1%" },
      { rotateZ: "14deg" },
    ],
  },
  loginInputs: {
    // position: "relative",
    flex: 1,
    padding: 8,
    gap: 8,
    paddingVertical: 40,
  },
  input: { backgroundColor: "#cfcfcf", minHeight: 40 },
  loginButton: {
    width: 60,
    aspectRatio: 1,
    borderRadius: "100%",
    overflow: "hidden",
    margin: 15,
    marginHorizontal: 20,
    right: 0,
    bottom: 0,
    position: "absolute",
    transform: [{ translateY: 60 }],
  },
  loginButtonLayout: {
    width: "100%",
    height: "100%",
  },
  loginButtonBG: {
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  loginButtonIcon: {
    flex: 1,
    textAlign: "center",
    textAlignVertical: "center",
  },

  footerLayout: { height: 500, margin: 20 },
  footerBody: {
    overflow: "hidden",
    top: -90,
  },
  footerCard: {
    width: "100%",
    height: 120,
    backgroundColor: "#fff",
    borderRadius: 40,
    borderStartStartRadius: 0,
    marginTop: 80,
  },
  footerCardFooter: {
    width: "102%",
    height: 100,
    backgroundColor: "#fff",
    borderRadius: 50,
    borderBottomLeftRadius: 30,
    borderBottomStartRadius: 10,
    position: "absolute",
    top: 0,
    transform: [
      { translateY: "-38%" },
      { translateX: "-1%" },
      { rotateZ: "14deg" },
    ],
  },
  alreadyAccountText: { marginTop: "auto", alignSelf: "center" },
  signUpButton: {
    borderRadius: 22.5,
    overflow: "hidden",
    margin: 15,
    marginHorizontal: 20,
    minHeight: 45,
  },
  signUpButtonLayout: {
    flex: 1,
  },
  signUpButtonBG: {
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  signUpButtonText: {
    flex: 1,
    textAlign: "center",
    textAlignVertical: "center",
    color: "#fff",
    fontWeight: "bold",
    fontSize: 18,
  },
});
